### ISSUE TITLE
Corrupted model weights

### ISSUE THREAD

**Issue by BradBalderson** [AIRI-Institute/DeepCT#75]
Hi,

I think the model weights pickle file is corrupted, when running the tutorial, when I get to this code block:
```
model_path = "DeepCT/tutorial/qDeepCT_model_state_dict.pt"
if torch.cuda.is_available():
    device = torch.device("cuda:0")
else:
    device = torch.device("cpu")
checkpoint = torch.load(model_path, map_location=device)
print(checkpoint.keys())
```

I get:
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-11-57f4b993f332>](https://localhost:8080/#) in <cell line: 6>()
      4 else:
      5     device = torch.device("cpu")
----> 6 checkpoint = torch.load(model_path, map_location=device)
      7 print(checkpoint.keys())

1 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1031             "functionality.")
   1032 
-> 1033     magic_number = pickle_module.load(f, **pickle_load_args)
   1034     if magic_number != MAGIC_NUMBER:
   1035         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'v'.

**Comment by msindeeva** [comment]
I was able to reproduce this problem. The problem is not with the corrupted weights, but with the fact that one of the commands in the tutorial (`! git lfs pull origin`) was unable to pull the necessary files from git LFS (due to our organization exceeding the data storage quota). I've reuploaded all the necessary files to our NextCloud server, and updated the tutorial, so it should work now.
Thank you for bringing this issue to light and sorry for such late reply!

**Comment by BradBalderson** [comment]
Thanks alot @msindeeva, really appreciate it! The tutorial is working now for me. 

Just a heads up that the same issue is also true for the inference repo here: https://github.com/AIRI-Institute/DeepCT-inference-helper 

Quick question, are the model weights on the inference repo and the weights here the same? 

They have different names so just wanted to check which one is the latest, we want to do inference with DeepCT :)

**Comment by BradBalderson** [comment]
Quick question, are the model weights on the inference repo and the weights here the same?

They have different names so just wanted to check which one is the latest, we want to do inference with DeepCT :)

**Comment by msindeeva** [comment]
@BradBalderson I've updated the DeepCT-inference-helper repo as well and answered there 
AIRI-Institute/DeepCT-inference-helper#1
